version: '3'

services:
  product-service:
    build: ./Api
    volumes:
      - ./Api:/var/www/html
    ports:
      - 5001:80

  website:
    image: php:apache
    volumes:
      - ./src:/var/www/html
    ports:
      - 5000:80
    depends_on:
      - product-service